apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name     : root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name     : sa-dev-cluster
    namespace: argocd
  source:
    path   : "demo-dev/applications"
    repoURL: "git@github.com:bagrat92/argocd.git"
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
      